### PR TITLE
Fix csr2parcsr

### LINKED ISSUE #1240: ij interface's -fromonecsrfile option failed
Hi,

I'm writing to ask about the `-fromonecsrfile` option in `hypre/src/test/ij.c`. It seems that there have been some updates to the way that the csr file is read since commit `4b94dac55df1b73f2c092227a08036f7b4797162`. In particular, I've been using the `-fromonecsrfile` option to pass in the matrix, which now fails in the current version. To recreate the issue, please download the following:

[hypre-ij-file.zip](https://github.com/user-attachments/files/18985563/hypre-ij-file.zip)

Then run the following command:
```
./ij -solver 1  -fromonecsrfile mat.txt -rhsfromonefile vec.txt -print -tol 1e-8
```

It prints the following error message:

```
=============================================
Hypre init times:
=============================================
Hypre init:
  wall clock time = 0.000002 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.000002 seconds
  cpu MFLOPS      = 0.000000


Using HYPRE_DEVELOP_STRING: v2.32.0-29-gff594b2d3 (branch master; the develop branch)

Running with these driver parameters:
  solver ID    = 1

  FromFile: mat.txt
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

The matrix is a 3 by 3 matrix with all one entries, except for at (1-based) row 3, column 3, which is zero.

Any help would be really appreciated, many thanks!

Rick

### PR DESCRIPTION
**Pull request by liruipeng**
Fixes #1240.

### CODE REVIEW

File: src/parcsr_mv/par_csr_matrix.c [hunk 1]
```diff
@@ -1835,6 +1835,8 @@ hypre_CSRMatrixToParCSRMatrix( MPI_Comm         comm,
    HYPRE_Int          *num_nonzeros_proc;
    HYPRE_BigInt        row_starts[2];
    HYPRE_BigInt        col_starts[2];
+   HYPRE_Int           valid_row_starts = 0;
+   HYPRE_Int           valid_col_starts = 0;
```
Comment (victorapm) [inline src/parcsr_mv/par_csr_matrix.c:1839]:
```suggestion
   HYPRE_BigInt        row_starts[2] = {0, 0};
   HYPRE_BigInt        col_starts[2] = {0, 0};
```

Maybe this solution is enough and doesn't require the addition of the `valid` variables

**Review by victorapm — APPROVED** [review]
Thanks @liruipeng

File: src/parcsr_mv/par_csr_matrix.c (hunk 1 above)
Comment (victorapm) [reply src/parcsr_mv/par_csr_matrix.c:1839]: Nevermind, this won't work. Sorry for the confusion

**Review by rfalgout — APPROVED** [review]

**Review by ulrikeyang — APPROVED** [review]
Looks good. Thanks
