### PR TITLE
Fix ILU solve

### LINKED ISSUE #984: GMRES + ILU crash in 2.29
|  Platform  |      Compiler      |      HYPRE version      |
|:----------:|:------------------:|:-----------------------:|
| Windows 10 | Visual Studio 2022 | 2.29.0 (OpenMP, no MPI) |

Using GMRES + HYPRE ILU works in HYPRE 2.26 but a memory access violation occurs in `hypre_ILUSolveLU` in HYPRE 2.29.

**NOTE**&mdash;In the following C++ example, preprocessor macro `IF_YOU_DEFINE_THIS_22900_WORKS` identifies a block of code by removing which 2.29 **actually works**.

\
HYPRE configuration:
```
cmake -G"Visual Studio 2022" -Ax64 -Thost=x64 -DHYPRE_INSTALL_PREFIX=C:/sw/hypre/msvc-2022/2.29.0 -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON -DHYPRE_ENABLE_SHARED=ON -DCMAKE_DEBUG_POSTFIX=d -DHYPRE_WITH_MPI=OFF -DHYPRE_WITH_OPENMP=ON -S src -B src/cmbuild
cmake --build src/cmbuild --config Debug
cmake --build src/cmbuild --config Release
cmake --install src/cmbuild --config Debug
cmake --install src/cmbuild --config Release
```
File `CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.27)

set(tgt HYPREErr)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS ON)
project(${tgt} LANGUAGES CXX)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/out-$<CONFIG>")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")

find_package(HYPRE 2.29.0 EXACT REQUIRED CONFIG)

# Need this instead of "OpenMP::OpenMP_C" because this project is C++
set_target_properties(HYPRE::HYPRE PROPERTIES INTERFACE_LINK_LIBRARIES "OpenMP::OpenMP_CXX")

# Copy DLLs to output directory
get_target_property(HYPRE_RUNTIME_LIBRARY_DEBUG   HYPRE::HYPRE IMPORTED_LOCATION_DEBUG)
get_target_property(HYPRE_RUNTIME_LIBRARY_RELEASE HYPRE::HYPRE IMPORTED_LOCATION_RELEASE)
file(COPY ${HYPRE_RUNTIME_LIBRARY_DEBUG}   DESTINATION "${CMAKE_BINARY_DIR}/out-Debug")
file(COPY ${HYPRE_RUNTIME_LIBRARY_RELEASE} DESTINATION "${CMAKE_BINARY_DIR}/out-Release")

add_executable(${tgt} ${tgt}.cpp)
target_link_libraries(${tgt} PRIVATE HYPRE::HYPRE)
```
File `HYPREErr.cpp`:
```cpp
#include <HYPRE.h>
#include <HYPRE_parcsr_ls.h>

#include <exception>
#include <iostream>
#include <vector>

#ifndef hypre_MPI_COMM_WORLD
#define hypre_MPI_COMM_WORLD 0
#endif

void
chk(HYPRE_Int ierr)
{
    if (ierr == 0)
        return;
    char errMsg[1024];
    HYPRE_DescribeError(ierr, errMsg);
    std::cout << "HYPRE ERROR: " << errMsg << std::endl;
    throw std::runtime_error(errMsg);
}

int
main()
{
    constexpr HYPRE_BigInt np {7};
    constexpr HYPRE_BigInt ilow {0};
    constexpr HYPRE_BigInt iup {np - 1};
    constexpr HYPRE_BigInt jlow {0};
    constexpr HYPRE_BigInt jup {np - 1};

    std::vector<HYPRE_BigInt> rows {0, 1, 2, 3, 4, 5, 6};   // np
    std::vector<HYPRE_BigInt> ncols {4, 3, 4, 3, 4, 3, 4};  // np
    const std::vector<HYPRE_BigInt> cols {0, 2, 4, 6,
                                            1, 3, 5,
                                          0, 2, 4, 6,
                                            1, 3, 5,
                                          0, 2, 4, 6,
                                            1, 3, 5,
                                          0, 2, 4, 6};  // nnz
    const std::vector<HYPRE_Complex> aValues {1.0,      0.3,      0.5,      0.7,
                                                   3.0,      0.5,      0.7,
                                              0.3,      5.0,      0.7,      0.9,
                                                   0.5,      7.0,      0.9,
                                              0.5,      0.7,      9.0,      1.1,
                                                   0.7,      0.9,     11.0,
                                              0.7,      0.9,      1.1,     13.0};  // nnz
    const std::vector<HYPRE_Complex> bValues {93.0, 122.0, 251.0, 344.0, 553.0, 710.0, 999.0};  // np
    std::vector<HYPRE_Complex> solution(np);

    try
    {
        HYPRE_IJMatrix ijA {};

#if HYPRE_RELEASE_NUMBER >= 22900
        chk(HYPRE_Initialize());
#else
        chk(HYPRE_Init());
#endif
        chk(HYPRE_IJMatrixCreate(hypre_MPI_COMM_WORLD, ilow, iup, jlow, jup, &ijA));
        chk(HYPRE_IJMatrixSetObjectType(ijA, HYPRE_PARCSR));
        chk(HYPRE_IJMatrixInitialize(ijA));
        chk(HYPRE_IJMatrixSetValues(ijA, np, ncols.data(), rows.data(), cols.data(), aValues.data()));
        chk(HYPRE_IJMatrixAssemble(ijA));

        HYPRE_ParCSRMatrix hypreA {};
        chk(HYPRE_IJMatrixGetObject(ijA, (void**)&hypreA));

        HYPRE_IJVector ijB {};
        chk(HYPRE_IJVectorCreate(hypre_MPI_COMM_WORLD, jlow, jup, &ijB));
        chk(HYPRE_IJVectorSetObjectType(ijB, HYPRE_PARCSR));
        chk(HYPRE_IJVectorInitialize(ijB));
        chk(HYPRE_IJVectorSetValues(ijB, np, rows.data(), bValues.data()));
        chk(HYPRE_IJVectorAssemble(ijB));

        HYPRE_ParVector hypreB {};
        chk(HYPRE_IJVectorGetObject(ijB, (void**)&hypreB));

        HYPRE_IJVector ijSolution {};
        chk(HYPRE_IJVectorCreate(hypre_MPI_COMM_WORLD, jlow, jup, &ijSolution));
        chk(HYPRE_IJVectorSetObjectType(ijSolution, HYPRE_PARCSR));
        chk(HYPRE_IJVectorInitialize(ijSolution));
        chk(HYPRE_IJVectorSetValues(ijSolution, np, rows.data(), solution.data()));
        chk(HYPRE_IJVectorAssemble(ijSolution));

        HYPRE_ParVector hypreSolution {};
        chk(HYPRE_IJVectorGetObject(ijSolution, (void**)&hypreSolution));

        HYPRE_PtrToParSolverFcn precondFcn = (HYPRE_PtrToParSolverFcn)HYPRE_ILUSolve;
        HYPRE_PtrToParSolverFcn precondSetupFcn = (HYPRE_PtrToParSolverFcn)HYPRE_ILUSetup;

        HYPRE_Solver precondSolver {};
        chk(HYPRE_ILUCreate(&precondSolver));
        chk(HYPRE_ILUSetType(precondSolver, 0));
        chk(HYPRE_ILUSetPrintLevel(precondSolver, 3));
#ifndef IF_YOU_DEFINE_THIS_22900_WORKS
        chk(HYPRE_ILUSetMaxIter(precondSolver, 1));
        chk(HYPRE_ILUSetTol(precondSolver, 0.0));
        chk(HYPRE_ILUSetLevelOfFill(precondSolver, 1));
        chk(HYPRE_ILUSetLocalReordering(precondSolver, 0));
        chk(HYPRE_ILUSetDropThreshold(precondSolver, 1e-5));
#endif
        HYPRE_Solver hypreSolver {};
        chk(HYPRE_ParCSRGMRESCreate(hypre_MPI_COMM_WORLD, &hypreSolver));
        chk(HYPRE_ParCSRGMRESSetPrecond(hypreSolver, precondFcn, precondSetupFcn, precondSolver));
        chk(HYPRE_ParCSRGMRESSetup(hypreSolver, hypreA, hypreB, hypreSolution));
        chk(HYPRE_ParCSRGMRESSolve(hypreSolver, hypreA, hypreB, hypreSolution));

        chk(HYPRE_ParVectorGetValues(hypreSolution, np, rows.data(), solution.data()));

        chk(HYPRE_ParCSRGMRESDestroy(hypreSolver));
        chk(HYPRE_ILUDestroy(precondSolver));
        chk(HYPRE_IJMatrixDestroy(ijA));
        chk(HYPRE_IJVectorDestroy(ijB));
        chk(HYPRE_IJVectorDestroy(ijSolution));

        chk(HYPRE_Finalize());
    }
    catch (...)
    {}
}
```

### PR DESCRIPTION
**Pull request by victorapm**
This PR fixes a segmentation fault that happens on ILU solve when not using reordering and running on host.

### CODE REVIEW

File: src/parcsr_ls/par_ilu_solve.c [hunk 1]
```diff
@@ -954,62 +958,59 @@ hypre_ILUSolveLUIter(hypre_ParCSRMatrix *A,
    /* copy rhs to account for diagonal of L (which is identity) */
 
    /* Initialize iteration to 0 */
-   for ( i = 0; i < nLU; i++ )
+   for (i = 0; i < nLU; i++)
    {
-      utemp_data[perm[i]] = 0.0;
+      utemp_data[i] = 0.0;
```
Comment (oseikuffuor1) [inline src/parcsr_ls/par_ilu_solve.c]: @victorapm is this setting the entire array to zero? Or was the original meant to only change part of the array? i.e. Is utemp_data expected to be the same size as nLU always?

**Review by oseikuffuor1 — COMMENTED** [review]
@victorapm after further review and talking to a few ppl on what the best approach(es) could be, I recommend a couple-ish options:
1. Be more explicit about what to do if perm is NULL or not. This can be achieved by just doing something like what you had in your previous commit ( commit: 74150f76e0e687835997c9851880ac4e270ed89c) before introducing the macro. It is not as concise as the macro,  but it is clear what is happening and does not have the possible runtime segfault.
2. (Always) initialize perm and qperm as identity (only needs to happen once) then use the macro as a strategy for fast indexing. This is the best of both worlds but leaves the possibility that a slower indexing approach might be used (albeit without a segfault). 

There are a lot of other places in the ilu code where we access the perm arrays directly (the slow way), and I am worried that familiarity with that part of the code will make a segfault on a similar call quite confusing. Eventually we can  perhaps optimize everything to use the macro and make it more standard.

I also have one additional comment on the PR pending your review about setting utem_data[i] = 0.0; Line 963.

**Review by liruipeng — APPROVED** [review]

**Review by oseikuffuor1 — APPROVED** [review]
