### PR TITLE
Fix dirent

### LINKED ISSUE #989: Compillation error (missing dirent.h)
If I configure HYPRE form the current master (14b5544d8b6d72c1e11e9732f42502fb9003700a) as follows:
```
cmake -G"Visual Studio 17 2022" -Ax64 -Thost=x64 -DHYPRE_INSTALL_PREFIX=C:/sw/hypre-2.29-master -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON -DHYPRE_ENABLE_SHARED=ON -DCMAKE_DEBUG_POSTFIX=d -DHYPRE_WITH_MPI=OFF -DHYPRE_WITH_OPENMP=ON -S src -B src/cmbuild
```
and build it as either:
```
cmake --build src/cmbuild --config Debug
cmake --build src/cmbuild --config Release
```
I get:
```
src\utilities\utilities.c(10,10): fatal  error C1083: Cannot open include file: 'dirent.h': No such file or directory
```

### PR DESCRIPTION
**Pull request by victorapm**
Avoids including a header file not present in Windows.

PS: tested with MSVC 2022 (version 17.0)

Closes #989

### CODE REVIEW

File: src/utilities/utilities.c [hunk 1]
```diff
@@ -169,6 +188,9 @@ hypre_CreateNextDirOfSequence(const char *basepath, const char *prefix, char **f
       }
    }
    closedir(dir);
+#else
+   /* TODO (VPM) */
```
Comment (victorapm) [inline src/utilities/utilities.c:192]: @rfalgout I will implement this code block in another PR. The intention here is mainly to fix compilation in Windows. Sorry for overlooking this before...

**Review by rfalgout — APPROVED** [review]
Looks good to me.  Thanks!
